"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { utilityApi } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Loader2, Sparkles } from "lucide-react";
import dynamic from "next/dynamic";

const MDEditor = dynamic(() => import("@uiw/react-md-editor").then((mod) => mod.default.Markdown), {
  ssr: false,
});

export default function CareerGuidancePage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [advice, setAdvice] = useState("");
  const [formData, setFormData] = useState({
    current_skills: "",
    experience_level: "",
    career_goals: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setAdvice("");

    try {
      const response = await utilityApi.post("/api/ai/career-guide", {
        current_skills: formData.current_skills.split(",").map((s) => s.trim()),
        experience_level: formData.experience_level,
        career_goals: formData.career_goals,
      });

      setAdvice(response.data.advice);
      toast.success("Career guidance generated!");
    } catch (error: any) {
      toast.error(error.response?.data?.error || "Failed to generate guidance");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Button variant="ghost" onClick={() => router.back()} className="mb-6">
          ← Back
        </Button>

        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2 flex items-center gap-3">
            <Sparkles className="h-10 w-10 text-blue-600" />
            AI Career Guidance
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Get personalized career advice powered by AI
          </p>
        </div>

        {/* Input Form */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Tell us about yourself</CardTitle>
            <CardDescription>
              Provide your current skills, experience, and career goals
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="skills">Current Skills (comma-separated) *</Label>
                <Input
                  id="skills"
                  value={formData.current_skills}
                  onChange={(e) => setFormData({ ...formData, current_skills: e.target.value })}
                  required
                  placeholder="e.g. JavaScript, React, Python, SQL"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="experience">Experience Level *</Label>
                <Input
                  id="experience"
                  value={formData.experience_level}
                  onChange={(e) => setFormData({ ...formData, experience_level: e.target.value })}
                  required
                  placeholder="e.g. 2 years as a frontend developer"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="goals">Career Goals *</Label>
                <Textarea
                  id="goals"
                  value={formData.career_goals}
                  onChange={(e) => setFormData({ ...formData, career_goals: e.target.value })}
                  required
                  rows={4}
                  placeholder="e.g. I want to become a senior full-stack engineer at a tech company"
                />
              </div>

              <Button type="submit" disabled={isLoading} className="w-full">
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Advice...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Get Career Advice
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Results */}
        {advice && (
          <Card>
            <CardHeader>
              <CardTitle>Your Personalized Career Advice</CardTitle>
              <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose dark:prose-invert max-w-none">
                <MDEditor source={advice} />
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
